image: ubuntu:latest

stages:
  - format
  - build
  - test

format:
  stage: format
  script:
    - apt-get update && apt-get install -y clang-format git
    - clang-format -i src/*.cpp include/*.h
    - git diff --exit-code

build:
  stage: build
  dependencies:
    - format
  script:
    - apt-get update && apt-get install -y clang cmake libfuse-dev libgtest-dev libsodium-dev pkg-config
    - mkdir build && cd build
    - cmake ../ && make
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  stage: test
  dependencies:
    - build
  script:
    - apt-get update && apt-get install -y libfuse-dev libgtest-dev libsodium-dev
    - cd build
    - ./customvfs_tests --no-cleanup > test_output.txt || true
    - |
      if grep -q "PASSED" test_output.txt; then
        echo "Custom VFS tests PASSED. Continuing."
      else
        echo "Custom VFS tests FAILED. Stopping."
        exit 1
      fi