name: Format, build and test

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install build and test dependencies
        run: |
          apt-get update && apt-get install -y clang cmake libfuse-dev libgtest-dev libsodium-dev pkg-config libboost-program-options-dev

      - name: Build
        run: |
          mkdir build && cd build
          cmake ../ && make

      - name: Test
        run: |
          cd build
          ./customvfs_exec --mountpoint /tmp/customvfs
          ./customvfs_tests --mountpoint /tmp/customvfs