name: Format, build and test

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install build and test dependencies
        run: |
          apt-get update && apt-get install -y clang cmake libfuse-dev libgtest-dev libsodium-dev pkg-config libboost-program-options-dev
      - name: Build
        run: |
          mkdir build && cd build
          cmake ../ && make

      # Next stage is missing
      # - ./customvfs_exec --mountpoint /tmp/customvfs
      # That would need a runner with /dev/fuse mounted and the container to be privileged

      - name: Test
        run: |
          cd build
          ./tests/customvfs_tests --no-fuse
