name: Format, build and test

on: [ push, pull_request ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install format dependencies
        run: |
          apt-get update && apt-get install -y clang-format git

      - name: Format
        run: clang-format -i src/*.cpp include/*.h

      - name: Check for changes
        run: |
          git diff --quiet || (echo "Formatting changes detected. Please run 'clang-format -i src/*.cpp include/*.h' and commit the changes." && exit 1)

      - name: Install build and test dependencies
        run: |
          apt-get update && apt-get install -y clang cmake libfuse-dev libgtest-dev libsodium-dev pkg-config libboost-program-options-dev

      - name: Build
        run: |
          mkdir build && cd build
          cmake ../ && make

      - name: Test
        run: |
          cd build
          ./customvfs --mountpoint /tmp/customvfs -f "-d -f"
          ./customvfs_tests --mountpoint /tmp/customvfs